amcl:
  ros__parameters:
    use_sim_time: true

    # Frames
    global_frame_id: map
    odom_frame_id: robot2/odom
    base_frame_id: robot2/base_footprint

    # TF
    tf_broadcast: true

    # Laser
    scan_topic: /robot2/scan
    laser_max_range: 12.0
    laser_min_range: 0.3
    laser_likelihood_max_dist: 2.0

    # AMCL update thresholds
    update_min_d: 0.05
    update_min_a: 0.05

    # Motion model
    robot_model_type: "nav2_amcl::DifferentialMotionModel"

    # Particle filter
    min_particles: 500
    max_particles: 2000
    pf_err: 0.05
    pf_z: 0.99

    # Laser model
    laser_model_type: "likelihood_field"

    sigma_hit: 0.2
    z_hit: 0.5
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.5

    # Beam settings
    max_beams: 60

    # Initial pose
    set_initial_pose: true
    always_reset_initial_pose: false
    initial_pose:
      x: 2.0000
      y: -6.2999
      z: 0.0
      yaw: 1.5700
    
    # Recovery
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0

    # Timing
    transform_tolerance: 1.0
