robot1:
  amcl:
    ros__parameters:
      use_sim_time: true

      alpha1: 0.2
      alpha2: 0.2
      alpha3: 0.2
      alpha4: 0.2
      alpha5: 0.2

      base_frame_id: robot1/base_footprint
      odom_frame_id: robot1/odom
      global_frame_id: map

      scan_topic: /robot1/scan

      tf_broadcast: true

      min_particles: 500
      max_particles: 2000
      laser_max_range: 12.0
      laser_min_range: 0.3

      update_min_d: 0.2
      update_min_a: 0.2

      transform_tolerance: 1.0

      set_initial_pose: false


  bt_navigator:
    ros__parameters:
      use_sim_time: true

      global_frame: map
      robot_base_frame: robot1/base_footprint
      odom_topic: /robot1/odom

      default_server_timeout: 20
      enable_groot_monitoring: false

      navigators: ["navigate_to_pose", "navigate_through_poses"]

      navigate_to_pose:
        plugin: "nav2_bt_navigator::NavigateToPoseNavigator"

      navigate_through_poses:
        plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"


  controller_server:
    ros__parameters:
      use_sim_time: true

      controller_frequency: 10.0

      min_x_velocity_threshold: 0.001
      min_y_velocity_threshold: 0.001
      min_theta_velocity_threshold: 0.001

      odom_topic: /robot1/odom

      progress_checker_plugins: ["progress_checker"]
      goal_checker_plugins: ["goal_checker"]
      controller_plugins: ["FollowPath"]

      progress_checker:
        plugin: "nav2_controller::SimpleProgressChecker"
        required_movement_radius: 0.5
        movement_time_allowance: 10.0

      goal_checker:
        plugin: "nav2_controller::SimpleGoalChecker"
        xy_goal_tolerance: 0.25
        yaw_goal_tolerance: 0.25
        stateful: true

      FollowPath:
        plugin: "dwb_core::DWBLocalPlanner"

        min_vel_x: 0.0
        max_vel_x: 0.5

        min_vel_theta: 0.0
        max_vel_theta: 1.0

        acc_lim_x: 2.5
        acc_lim_theta: 3.2

        decel_lim_x: -2.5
        decel_lim_theta: -3.2

        vx_samples: 20
        vtheta_samples: 20

        sim_time: 1.7

        xy_goal_tolerance: 0.25
        trans_stopped_velocity: 0.1

        critics:
          - RotateToGoal
          - Oscillation
          - BaseObstacle
          - GoalAlign
          - PathAlign
          - PathDist
          - GoalDist


  local_costmap:
    local_costmap:
      ros__parameters:
        use_sim_time: true

        global_frame: robot1/odom
        robot_base_frame: robot1/base_footprint

        rolling_window: true

        width: 3.0
        height: 3.0
        resolution: 0.05

        robot_radius: 0.12

        plugins:
          - obstacle_layer
          - inflation_layer

        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"

          observation_sources: scan

          scan:
            topic: /robot1/scan
            data_type: LaserScan
            clearing: true
            marking: true
            obstacle_max_range: 12.0
            raytrace_max_range: 12.0

        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          inflation_radius: 0.3


  global_costmap:
    global_costmap:
      ros__parameters:
        use_sim_time: true

        global_frame: map
        robot_base_frame: robot1/base_footprint

        resolution: 0.05

        robot_radius: 0.12

        track_unknown_space: true

        plugins:
          - static_layer
          - obstacle_layer
          - inflation_layer

        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          map_topic: /map

        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"

          observation_sources: scan

          scan:
            topic: /robot1/scan
            data_type: LaserScan
            clearing: true
            marking: true
            obstacle_max_range: 12.0
            raytrace_max_range: 12.0

        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          inflation_radius: 0.3


  planner_server:
    ros__parameters:
      use_sim_time: true

      expected_planner_frequency: 5.0

      planner_plugins: ["GridBased"]

      GridBased:
        plugin: "nav2_navfn_planner::NavfnPlanner"
        tolerance: 0.5
        use_astar: false
        allow_unknown: true


  behavior_server:
    ros__parameters:
      use_sim_time: true

      global_frame: map
      robot_base_frame: robot1/base_footprint
      odom_topic: /robot1/odom

      behavior_plugins:
        - spin
        - backup
        - drive_on_heading
        - wait

      spin:
        plugin: "nav2_behaviors::Spin"

      backup:
        plugin: "nav2_behaviors::BackUp"

      drive_on_heading:
        plugin: "nav2_behaviors::DriveOnHeading"

      wait:
        plugin: "nav2_behaviors::Wait"


robot2:
  amcl:
    ros__parameters:
      use_sim_time: true
      base_frame_id: robot2/base_footprint
      odom_frame_id: robot2/odom
      global_frame_id: map
      scan_topic: /robot2/scan
      tf_broadcast: true

      min_particles: 500
      max_particles: 2000

      laser_max_range: 12.0
      laser_min_range: 0.3

      update_min_d: 0.2
      update_min_a: 0.2

      transform_tolerance: 1.0


  bt_navigator:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: robot2/base_footprint
      odom_topic: /robot2/odom


  controller_server:
    ros__parameters:
      use_sim_time: true
      controller_frequency: 10.0

      odom_topic: /robot2/odom

      min_x_velocity_threshold: 0.001
      min_y_velocity_threshold: 0.001
      min_theta_velocity_threshold: 0.001

      progress_checker_plugins: ["progress_checker"]
      goal_checker_plugins: ["goal_checker"]
      controller_plugins: ["FollowPath"]

      progress_checker:
        plugin: "nav2_controller::SimpleProgressChecker"
        required_movement_radius: 0.5
        movement_time_allowance: 10.0

      goal_checker:
        plugin: "nav2_controller::SimpleGoalChecker"
        xy_goal_tolerance: 0.25
        yaw_goal_tolerance: 0.25
        stateful: true

      FollowPath:
        plugin: "dwb_core::DWBLocalPlanner"

        max_vel_x: 0.5
        max_vel_theta: 1.0

        min_vel_x: 0.0
        min_vel_theta: 0.0

        acc_lim_x: 2.5
        acc_lim_theta: 3.2

        decel_lim_x: -2.5
        decel_lim_theta: -3.2

        vx_samples: 20
        vtheta_samples: 20

        sim_time: 1.7

        critics:
          - RotateToGoal
          - Oscillation
          - BaseObstacle
          - GoalAlign
          - PathAlign
          - PathDist
          - GoalDist


  local_costmap:
    local_costmap:
      ros__parameters:
        use_sim_time: true

        global_frame: robot2/odom
        robot_base_frame: robot2/base_footprint

        rolling_window: true

        width: 3.0
        height: 3.0

        resolution: 0.05
        robot_radius: 0.12

        plugins:
          - obstacle_layer
          - inflation_layer

        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"

          observation_sources: scan

          scan:
            topic: /robot2/scan
            data_type: LaserScan
            clearing: true
            marking: true
            obstacle_max_range: 12.0
            raytrace_max_range: 12.0

        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          inflation_radius: 0.3


  global_costmap:
    global_costmap:
      ros__parameters:
        use_sim_time: true

        global_frame: map
        robot_base_frame: robot2/base_footprint

        resolution: 0.05
        robot_radius: 0.12

        plugins:
          - static_layer
          - obstacle_layer
          - inflation_layer

        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          map_topic: /map

        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"

          observation_sources: scan

          scan:
            topic: /robot2/scan
            data_type: LaserScan
            clearing: true
            marking: true
            obstacle_max_range: 12.0
            raytrace_max_range: 12.0

        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          inflation_radius: 0.3


  planner_server:
    ros__parameters:
      use_sim_time: true

      planner_plugins: ["GridBased"]

      GridBased:
        plugin: "nav2_navfn_planner::NavfnPlanner"
        tolerance: 0.5
        use_astar: false
        allow_unknown: true


  behavior_server:
    ros__parameters:
      use_sim_time: true

      global_frame: map
      robot_base_frame: robot2/base_footprint
      odom_topic: /robot2/odom


robot3:
  amcl:
    ros__parameters:
      use_sim_time: true
      base_frame_id: robot3/base_footprint
      odom_frame_id: robot3/odom
      global_frame_id: map
      scan_topic: /robot3/scan
      tf_broadcast: true

      min_particles: 500
      max_particles: 2000

      laser_max_range: 12.0
      laser_min_range: 0.3

      update_min_d: 0.2
      update_min_a: 0.2

      transform_tolerance: 1.0


  bt_navigator:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: robot3/base_footprint
      odom_topic: /robot3/odom


  controller_server:
    ros__parameters:
      use_sim_time: true
      controller_frequency: 10.0

      odom_topic: /robot3/odom

      min_x_velocity_threshold: 0.001
      min_y_velocity_threshold: 0.001
      min_theta_velocity_threshold: 0.001

      progress_checker_plugins: ["progress_checker"]
      goal_checker_plugins: ["goal_checker"]
      controller_plugins: ["FollowPath"]

      progress_checker:
        plugin: "nav2_controller::SimpleProgressChecker"
        required_movement_radius: 0.5
        movement_time_allowance: 10.0

      goal_checker:
        plugin: "nav2_controller::SimpleGoalChecker"
        xy_goal_tolerance: 0.25
        yaw_goal_tolerance: 0.25
        stateful: true

      FollowPath:
        plugin: "dwb_core::DWBLocalPlanner"

        max_vel_x: 0.5
        max_vel_theta: 1.0

        min_vel_x: 0.0
        min_vel_theta: 0.0

        acc_lim_x: 2.5
        acc_lim_theta: 3.2

        decel_lim_x: -2.5
        decel_lim_theta: -3.2

        vx_samples: 20
        vtheta_samples: 20

        sim_time: 1.7

        critics:
          - RotateToGoal
          - Oscillation
          - BaseObstacle
          - GoalAlign
          - PathAlign
          - PathDist
          - GoalDist


  local_costmap:
    local_costmap:
      ros__parameters:
        use_sim_time: true

        global_frame: robot3/odom
        robot_base_frame: robot3/base_footprint

        rolling_window: true

        width: 3.0
        height: 3.0

        resolution: 0.05
        robot_radius: 0.12

        plugins:
          - obstacle_layer
          - inflation_layer

        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"

          observation_sources: scan

          scan:
            topic: /robot3/scan
            data_type: LaserScan
            clearing: true
            marking: true
            obstacle_max_range: 12.0
            raytrace_max_range: 12.0

        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          inflation_radius: 0.3


  global_costmap:
    global_costmap:
      ros__parameters:
        use_sim_time: true

        global_frame: map
        robot_base_frame: robot3/base_footprint

        resolution: 0.05
        robot_radius: 0.12

        plugins:
          - static_layer
          - obstacle_layer
          - inflation_layer

        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          map_topic: /map

        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"

          observation_sources: scan

          scan:
            topic: /robot3/scan
            data_type: LaserScan
            clearing: true
            marking: true
            obstacle_max_range: 12.0
            raytrace_max_range: 12.0

        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          inflation_radius: 0.3


  planner_server:
    ros__parameters:
      use_sim_time: true

      planner_plugins: ["GridBased"]

      GridBased:
        plugin: "nav2_navfn_planner::NavfnPlanner"
        tolerance: 0.5
        use_astar: false
        allow_unknown: true


  behavior_server:
    ros__parameters:
      use_sim_time: true

      global_frame: map
      robot_base_frame: robot3/base_footprint
      odom_topic: /robot3/odom
