#!/usr/bin/env python3

import os

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import AnyLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution, Command
from launch_ros.actions import Node
from ament_index_python.packages import get_package_share_directory


def generate_launch_description():

    # =========================================================
    # PACKAGE
    # =========================================================

    pkg_virtual_lab = get_package_share_directory('virtual_lab')

    # Add package share directory to Gazebo resource path
    gazebo_models_path, _ = os.path.split(pkg_virtual_lab)

    existing_gz_path = os.environ.get('GZ_SIM_RESOURCE_PATH', '')

    if gazebo_models_path not in existing_gz_path.split(os.pathsep):
        if existing_gz_path:
            os.environ['GZ_SIM_RESOURCE_PATH'] = (
                existing_gz_path + os.pathsep + gazebo_models_path
            )
        else:
            os.environ['GZ_SIM_RESOURCE_PATH'] = gazebo_models_path


    # =========================================================
    # ARGUMENTS
    # =========================================================

    world_arg = DeclareLaunchArgument(
        'world',
        default_value='logistics_warehouse.sdf',
        description='Gazebo world file'
    )

    model_arg = DeclareLaunchArgument(
        'model',
        default_value='mogi_bot.urdf.xacro',
        description='Robot xacro file'
    )


    # =========================================================
    # ROBOT DESCRIPTION
    # =========================================================

    urdf_file_path = PathJoinSubstitution([
        pkg_virtual_lab,
        'urdf',
        LaunchConfiguration('model')
    ])


    # =========================================================
    # GAZEBO
    # =========================================================

    world_launch = IncludeLaunchDescription(
        AnyLaunchDescriptionSource(
            os.path.join(
                pkg_virtual_lab,
                'launch',
                'world.launch.xml'
            )
        ),
        launch_arguments={
            'world': LaunchConfiguration('world')
        }.items()
    )


    # =========================================================
    # COMMON ROBOT STATE PUBLISHER SETTINGS
    # =========================================================

    # IMPORTANT:
    #
    # Each robot gets its own namespace:
    #
    #   /robot1/tf
    #   /robot2/tf
    #   /robot3/tf
    #
    # and:
    #
    #   /robot1/tf_static
    #   /robot2/tf_static
    #   /robot3/tf_static
    #
    # The xacro receives robot_name so that the frame names
    # generated by the robot description are:
    #
    #   robot1/...
    #   robot2/...
    #   robot3/...
    #
    # rather than all robots using identical frame names.


    # =========================================================
    # ROBOT 1
    # =========================================================

    robot1_description = Command([
        'xacro ',
        urdf_file_path,
        ' robot_name:=robot1'
    ])

    robot1_state_publisher = Node(
        package='robot_state_publisher',
        executable='robot_state_publisher',

        namespace='robot1',
        name='robot_state_publisher',

        output='screen',

        parameters=[
            {
                'robot_description': robot1_description,
                'use_sim_time': True,
            }
        ],

        remappings=[
            ('/tf', '/tf'),
            ('/tf_static', '/tf_static'),
        ]
    )

    robot1_spawn = Node(
        package='ros_gz_sim',
        executable='create',

        arguments=[
            '-name', 'robot1',
            '-topic', '/robot1/robot_description',

            '-x', '4.88',
            '-y', '-6.30',
            '-z', '0.30',
            '-Y', '1.57',
        ],

        output='screen',

        parameters=[
            {
                'use_sim_time': True,
            }
        ]
    )


    # =========================================================
    # ROBOT 2
    # =========================================================

    robot2_description = Command([
        'xacro ',
        urdf_file_path,
        ' robot_name:=robot2'
    ])

    robot2_state_publisher = Node(
        package='robot_state_publisher',
        executable='robot_state_publisher',

        namespace='robot2',
        name='robot_state_publisher',

        output='screen',

        parameters=[
            {
                'robot_description': robot2_description,
                'use_sim_time': True,
            }
        ],

        remappings=[
            ('/tf', '/tf'),
            ('/tf_static', '/tf_static'),
        ]
    )

    robot2_spawn = Node(
        package='ros_gz_sim',
        executable='create',

        arguments=[
            '-name', 'robot2',
            '-topic', '/robot2/robot_description',

            '-x', '2.0',
            '-y', '-6.30',
            '-z', '0.30',
            '-Y', '1.57',
        ],

        output='screen',

        parameters=[
            {
                'use_sim_time': True,
            }
        ]
    )


    # =========================================================
    # ROBOT 3
    # =========================================================

    robot3_description = Command([
        'xacro ',
        urdf_file_path,
        ' robot_name:=robot3'
    ])

    robot3_state_publisher = Node(
        package='robot_state_publisher',
        executable='robot_state_publisher',

        namespace='robot3',
        name='robot_state_publisher',

        output='screen',

        parameters=[
            {
                'robot_description': robot3_description,
                'use_sim_time': True,
            }
        ],

        remappings=[
            ('/tf', '/tf'),
            ('/tf_static', '/tf_static'),
        ]
    )

    robot3_spawn = Node(
        package='ros_gz_sim',
        executable='create',

        arguments=[
            '-name', 'robot3',
            '-topic', '/robot3/robot_description',

            '-x', '-3.88',
            '-y', '-6.30',
            '-z', '0.30',
            '-Y', '1.57',
        ],

        output='screen',

        parameters=[
            {
                'use_sim_time': True,
            }
        ]
    )


    # =========================================================
    # GAZEBO -> ROS 2 BRIDGE
    # =========================================================

    gz_bridge_config = os.path.join(
        pkg_virtual_lab,
        'config',
        'gz_bridge.yaml'
    )

    gz_bridge_node = Node(
        package='ros_gz_bridge',
        executable='parameter_bridge',

        name='gz_bridge',

        parameters=[
            {
                'config_file': gz_bridge_config,
                'use_sim_time': True,
            }
        ],

        output='screen'
    )


    # =========================================================
    # IMAGE BRIDGE
    # =========================================================
    #
    # Keep this only if your mogi_bot contains a camera.
    #
    # The topic must match the topic generated by your SDF/URDF.
    #

    gz_image_bridge_node = Node(
        package='ros_gz_image',
        executable='image_bridge',

        arguments=[
            '/camera/image'
        ],

        output='screen',

        parameters=[
            {
                'use_sim_time': True,
                'camera.image.compressed.jpeg_quality': 75,
            }
        ]
    )


    # =========================================================
    # LAUNCH DESCRIPTION
    # =========================================================

    ld = LaunchDescription()

    # Arguments
    ld.add_action(world_arg)
    ld.add_action(model_arg)

    # Gazebo
    ld.add_action(world_launch)

    # Robot 1
    ld.add_action(robot1_state_publisher)
    ld.add_action(robot1_spawn)

    # Robot 2
    ld.add_action(robot2_state_publisher)
    ld.add_action(robot2_spawn)

    # Robot 3
    ld.add_action(robot3_state_publisher)
    ld.add_action(robot3_spawn)

    # Gazebo bridges
    ld.add_action(gz_bridge_node)
    ld.add_action(gz_image_bridge_node)

    return ld

